[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[main.params]
icon = "home"

[[main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
[main.params]
icon = "user"

[[main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30
[main.params]
icon = "archives"

[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40
[main.params]
icon = "search"

[[main]]
identifier = "links"
name = "Links"
url = "/links/"
weight = 50
[main.params]
icon = "link"

[[social]]
identifier = "kofi"
name = "Ko-fi"
url = "https://ko-fi.com/getfoss"
[social.params]
icon = "brand-kofi"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/GetFoss"
[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "X"
url = "https://x.com/GetFoss"
[social.params]
icon = "brand-x"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/getfoss"
[social.params]
icon = "brand-telegram"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.social/@GetFOSS"
[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "bluesky"
name = "Bluesky"
url = "https://bsky.app/profile/getfoss.org"
[social.params]
icon = "brand-bluesky"