mainSections = [
  "debian-ubuntu",
  "enterprise-linux",
  "security-privacy",
  "diy-advanced",
  "disk-system-utilities",
  "graphics-design",
  "engineering",
  "bsd-illumos",
  "independent-heritage",
  "other"
]
rssFullContent = true
favicon        = "/images/GetFOSS.webp"

[footer]
    since = 2026

[sidebar]
    emoji = ""
    subtitle = "Free as in Freedom"
    avatar = "/images/GetFOSS.webp"

[article]
    [article.license]
        enabled = true
        default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page     = [{ type = "toc" }]

[comments]
    enabled  = false
    provider = "disqus"

[cookies]
    enabled = false
    [cookies.categories]
        analytics  = true
        functional = true

[related]
    includeNewer = true
    threshold    = 60
    toLower      = false
    indices      = [
        { name = "tags", weight = 100 },
        { name = "categories", weight = 200 },
    ]